site_name: Geographische Informationssysteme 1
site_url: https://sitename.example

theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/UT_WBMW_Rot_RGB_v2.svg
  favicon: assets/ut_palme.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
  language: de
  palette:
      # Dark Mode
    - scheme: ut_dark
      toggle:
        icon: material/brightness-6
        name: Dark mode
      primary: custom
      accent: red
    # Light Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
      primary: grey
      accent: red

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 Geodatenmanager/-in, Universität Tübingen

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeowazM
    - icon: simple/youtube
      link: https://www.youtube.com/@geodatenwelten
